# Generated by Django 4.0.6 on 2022-12-01 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BannerImg', models.ImageField(upload_to='image')),
                ('BannerAlt', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('BrandName', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('SubCategory', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('brandname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.AutoField(primary_key=True, serialize=False)),
                ('ProductCode', models.CharField(max_length=50)),
                ('ProductName', models.CharField(max_length=50)),
                ('ProductTitle', models.CharField(max_length=50)),
                ('ProductPrice', models.DecimalField(decimal_places=0, max_digits=30)),
                ('ProductInfo', models.TextField(blank=True)),
                ('ProductStatus', models.CharField(max_length=30)),
                ('ProductImg1', models.ImageField(blank=True, upload_to='image')),
                ('ProductImg2', models.ImageField(blank=True, upload_to='image')),
                ('ProductImg3', models.ImageField(blank=True, upload_to='image')),
                ('ProductImg4', models.ImageField(blank=True, upload_to='image')),
                ('ProductImg5', models.ImageField(blank=True, upload_to='image')),
                ('ProductImg6', models.ImageField(blank=True, upload_to='image')),
                ('ProductImg7', models.ImageField(blank=True, upload_to='image')),
                ('ProductImg8', models.ImageField(blank=True, upload_to='image')),
                ('ProductImg9', models.ImageField(blank=True, upload_to='image')),
                ('ProductImg10', models.ImageField(blank=True, upload_to='image')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.category')),
            ],
        ),
    ]
